import Head from 'next/head'
import { useContext } from 'react'
import About from '../components/About'
import Main from '../components/Main'
import { MyContext } from '../context/Context'
export default function Home() {
  const {about}=useContext(MyContext)
  return (
    <div>
      <Head>
        <title>Random Users Hub &#x1F91F;</title>
        <meta name="description" content="Generated by Naqvi" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

           {about ? <About/>: <Main/> } 
    </div>
  )
}
