import Head from "next/head";
import Main from "../components/Main";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Random Users Hub &#x1F91F;</title>
        <meta name="description" content="Generated by Naqvi" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </div>
  );
}
